/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		git
#define VCS_BASENAME	ScreenshotFramer
#define VCS_UUID		bbe2397b961b6e54b179b29a6a8431389237c96b
#define VCS_NUM			146
#define VCS_DATE		2019-04-23T10:27:10Z
#define VCS_BRANCH		enhancement/homebrew
#define VCS_TAG			v1.0
#define VCS_TAG_OPENPGP	
#define VCS_TICK		43
#define VCS_EXTRA		

#define VCS_ACTION_STAMP	2019-04-23T10:27:10Z!patrick.kladek@outlook.com
#define VCS_FULL_HASH		86342c02b911d29795f405676f8085aa5005e925
#define VCS_COMMIT_OPENPGP	
#define VCS_SHORT_HASH		86342c0

#define VCS_WC_MODIFIED		1

#endif

/* end */
