/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"ScreenshotFramer"
#define VCS_UUID		"bbe2397b961b6e54b179b29a6a8431389237c96b"
#define VCS_NUM			147
#define VCS_DATE		"2019-04-23T14:32:18Z"
#define VCS_BRANCH		"enhancement/homebrew"
#define VCS_TAG			"v1.0"
#define VCS_TAG_OPENPGP	""
#define VCS_TICK		44
#define VCS_EXTRA		""

#define VCS_ACTION_STAMP	"2019-04-23T14:32:18Z!patrick.kladek@outlook.com"
#define VCS_FULL_HASH		"c732908ce16b71d0c73f0793f3c31b068e89fe4a"
#define VCS_COMMIT_OPENPGP	""
#define VCS_SHORT_HASH		"c732908"

#define VCS_WC_MODIFIED		1

#endif

/* end */
